# Generated by Django 4.1.5 on 2023-01-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='postcode',
        ),
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.IntegerField(default=None, verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
    ]
