# Generated by Django 4.1.5 on 2023-02-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0002_remove_office_postcode_address_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='link_to_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
