# Generated by Django 4.1.5 on 2023-02-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0003_office_link_to_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
    ]
