# Generated by Django 4.1.5 on 2023-02-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0004_office_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='link_to_picture',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='link_to_telegram',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на телеграм-аккаунт'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='link_to_vk',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на ВК-аккаунт'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='link_to_youtube',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на ютуб-канал'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='link_to_picture',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='office',
            name='link_to_picture',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_to_photo',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
